#Puerto de prueba
server.port=8080
spring.application.name=mail_whatsapp_send
spring.messages.basename=messages
spring.config.encoding=UTF-8

#Documentacion
springdoc.swagger-ui.url=/openapi.yaml

#Configuracion de filtro (Rate Limit)
rate.limit.capacity=999999
rate.limit.refill.capacity=999999
rate.limit.refill.minutes=1

#Configuracion de base de datos
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#Propiedad para resetear la base de datos
spring.jpa.hibernate.ddl-auto=update

# Configuracion para mandar mensajes de telegram
telegram.api.token=${TELEGRAM_API_TOKEN}
telegram.api.chat.id=${TELEGRAM_API_CHAT_ID}
telegram.api.uri=${TELEGRAM_API_URI}
telegram.api.domain=${TELEGRAM_API_DOMAIN}

# Formato de fecha
date.format=dd-MM-yyyy HH:mm:ss

# Mensaje
contact.from.message=Has recibido una nueva solicitud de contacto desde tu sitio web.\n\
\n\
Nombre: %s\n\
Correo electronico: %s\n\
\n\
Mensaje:\n\
%s\n\
\n\
Por favor, responde al usuario utilizando los datos de contacto proporcionados.

# Github
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}

# Vercel
vercel.rebuild.deploy.url=${VERCEL_REBUILD_DEPLOY_URL}

# Postiz
postiz.base.url=${POSTIZ_BASE_URL}
postiz.api.key=${POSTIZ_API_KEY}