#Puerto de prueba
server.port=8080
spring.application.name=mail_whatsapp_send
spring.messages.basename=messages
spring.config.encoding=UTF-8

#Documentacion
springdoc.swagger-ui.url=/openapi.yaml

#Configuracion de filtro (Rate Limit)
rate.limit.capacity=999999
rate.limit.refill.capacity=999999
rate.limit.refill.minutes=1

#Configuracion de la base de datos principal
spring.datasource.jdbc-url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuracion de la base de datos de hedgeDoc la secundaria
app.datasource.secondary.jdbc-url=jdbc:postgresql://${SECONDARY_DATABASE_HOST}:${SECONDARY_DATABASE_PORT}/${SECONDARY_DATABASE_NAME}
app.datasource.secondary.username=${SECONDARY_DATABASE_USER}
app.datasource.secondary.password=${SECONDARY_DATABASE_PASSWORD}
app.datasource.secondary.driver-class-name=org.postgresql.Driver

#Propiedad para resetear la base de datos
spring.jpa.hibernate.ddl-auto=update

# Configuracion para mandar mensajes de telegram
telegram.api.token=${TELEGRAM_API_TOKEN}
telegram.api.chat.id=${TELEGRAM_API_CHAT_ID}
telegram.api.uri=${TELEGRAM_API_URI}
telegram.api.domain=${TELEGRAM_API_DOMAIN}

# Formato de fecha
date.format=dd-MM-yyyy HH:mm:ss

# Mensaje
contact.from.message=Has recibido una nueva solicitud de contacto desde tu sitio web.\n\
\n\
Nombre: %s\n\
Correo electronico: %s\n\
\n\
Mensaje:\n\
%s\n\
\n\
Por favor, responde al usuario utilizando los datos de contacto proporcionados.

# Github
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}
github.api.url=https://api.github.com
github.api.uri.branch=/repos/{owner}/{repo}/contents/{filePath}?ref={branch}
github.api.uri=/repos/{owner}/{repo}/contents/{filePath}
github.api.uri.files=/repos/{owner}/{name}/git/trees/{branch}?recursive=1
github.api.uri.delete=/repos/{owner}/{repo}/contents/{filePath}

# Vercel
vercel.rebuild.deploy.url=${VERCEL_REBUILD_DEPLOY_URL}
vercel.webhook.secret=${VERCEL_WEBHOOK_SECRET}

# Postiz
postiz.base.url=${POSTIZ_BASE_URL}
postiz.api.key=${POSTIZ_API_KEY}

postiz.posts[0].integration.id=${POSTIZ_POSTS_0_INTEGRATION_ID}
postiz.posts[0].settings.__type=${POSTIZ_POSTS_0_SETTINGS__TYPE}

postiz.posts[1].integration.id=${POSTIZ_POSTS_1_INTEGRATION_ID}
postiz.posts[1].settings.__type=${POSTIZ_POSTS_1_SETTINGS__TYPE}

postiz.posts[2].integration.id=${POSTIZ_POSTS_2_INTEGRATION_ID}
postiz.posts[2].settings.__type=${POSTIZ_POSTS_2_SETTINGS__TYPE}

postiz.posts[3].integration.id=${POSTIZ_POSTS_3_INTEGRATION_ID}
postiz.posts[3].settings.__type=${POSTIZ_POSTS_3_SETTINGS__TYPE}
postiz.posts[3].settings.channel=${POSTIZ_POSTS_3_SETTINGS_CHANNEL}

postiz.posts[4].integration.id=${POSTIZ_POSTS_4_INTEGRATION_ID}
postiz.posts[4].settings.__type=${POSTIZ_POSTS_4_SETTINGS__TYPE}
postiz.posts[4].settings.who_can_reply_post=${POSTIZ_POSTS_4_SETTINGS_WHO_CAN_REPLY_POST}

# Mi pagina
mypage.url.base=https://www.gerardomarquez.dev/blog/posts/

# HedgeDoc
hedgedoc.url=http://localhost:3000
hedgedoc.url.download=/{noteId}/download
hedgedoc.url.new=/new
hedgedoc.url.info=/{locationid}/info

# Credenciales del panel de sync
sync.panel.username=${SYNC_PANEL_USERNAME}
sync.panel.password=${SYNC_PANEL_PASSWORD}