version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db_mail_whatsapp_send
    environment:
      POSTGRES_DB: mail_whatsapp_send
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/home/luisgmm/Documentos/Proyectos/web_gerardomarquez_dev/backend/mail_whatsapp_send/src/volume

volumes:
  pgdata: