services:
  db:
    image: postgres:16
    container_name: postgres_db_mail_whatsapp_send
    environment:
      POSTGRES_DB: mail_whatsapp_send
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - .volumes/postgres_db_mail_whatsapp_send:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_mail_whatsapp_send
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  postgres:
    image: postgres:15
    container_name: postgres_db_evolution_api
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: evolution_api_db
    ports:
      - "5433:5432"
    volumes:
      - .volumes/postgres_db_evolution_api:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .volumes/evolution_api:/evolution/instances
volumes:
  pgdata:
  postgres_data:
  evolution_instances: